iSchoolApp/admin/routes.py
# import stuff of flask
from flask import render_template, request, redirect, url_for, flash, send_file, Blueprint, session

# getting access to application in app folder and to database and to bcrypt of password
from flask_login import login_required

from iSchoolApp import db, handleImageUploads, recognize_video, bcrypt

# import form of register and login from app folder
from iSchoolApp.admin.forms import AdministerLogin

# import the database from app folder in file models
from iSchoolApp.models import User, Lecture, Administer, Report, Date, \
    Attendance
import os
import extract_embeddings
import train_model
from iSchoolApp.registerCam import registerCamFunc
from iSchoolApp.addCourse import addCourseFunc

admin = Blueprint('admin', __name__)


# Handler in loginAdmin users
@admin.route("/loginAdmin", methods=['GET', 'POST'])
def loginAdminister():
    form = AdministerLogin()
    if form.validate_on_submit():
        admin = Administer.query.filter_by(email=form.email.data).first()
        # check if email and password ok
        # if admin and bcrypt.check_password_hash(admin.password, form.password.data):
        if admin and bcrypt.check_password_hash(admin.password, form.password.data):
            session['admin'] = form.email.data
            # os.environ['ADMIN'] = 'in'
            return redirect(url_for('admin.AdminAccount'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('loginAdmin.html', form=form)


@admin.route("/logoutAdmin")
def logoutAdmin():
    session.pop('admin', None)
    return redirect(url_for('main_page.home'))


@admin.route("/AdminAccount", methods=['GET'])
def AdminAccount():
    if 'admin' in session:
        course_list = Lecture.query.all()
        return render_template('AdminAccount.html', course_list=course_list)
    return redirect(url_for('admin.loginAdminister'))


@admin.route("/onOffCameras", methods=["POST"])
def onOffCameras():
    act = request.form.get("button")
    print(act)
    if act == "1":
        os.environ['CAM'] = 'on'
        recognize_video.video_recognizer("face_detection_model", "openface_nn4.small2.v1.t7", "output/recognizer.pickle"
                                         , "output/le.pickle")
        return redirect((url_for('admin.AdminAccount')))

    elif act == "0":
        os.environ['CAM'] = 'off'
        return redirect((url_for('admin.AdminAccount')))


# train our model
@admin.route('/train', methods=['GET'])
def train():
    extract_embeddings.extract_embeddings_func("dataset", "output/embeddings.pickle",
                                               "face_detection_model", "openface_nn4.small2.v1.t7")
    train_model.train("output/embeddings.pickle", "output/recognizer.pickle", "output/le.pickle")
    return "blah"


# handler in upload a new image of new students to our database
@admin.route("/handleImageUpload", methods=['POST'])
def handleImagesFileUpload():
    handleImageUploads.handleImagesFileUpload()
    return redirect((url_for('admin.AdminAccount')))


@admin.route("/registerCam", methods=['POST'])
def registerCam():
    c = registerCamFunc()
    print(c)
    return redirect(url_for('admin.AdminAccount'))


@admin.route("/addCourse", methods=['POST'])
def addCourse():
    course_name = request.form.get("name")
    class_number = request.form.get("classNum")
    per = request.form.get("percentage")

    if Lecture.query.filter_by(nameOfLecture=course_name).first():
        flash('Course is already created. Please choice a different course', 'danger')
    else:
        addCourseFunc(course_name, class_number, per)
    return redirect((url_for('admin.AdminAccount')))


@admin.route("/addCourseToTeacher", methods=['POST'])
def addCourseToTeacher():
    teacher_name = request.form.get("teacher_name")
    teacher_id = request.form.get("teacher_id")

    user = User.query.filter_by(id=teacher_id).first()
    courses = request.form.getlist("course[]")
    message = ""
    if courses:
        for cou in courses:
            print(user.get_id())
            c = Lecture.query.filter_by(nameOfLecture=cou).first()
            if c.user_id is None:
                c.user_id = user.get_id()
                db.session.commit()
                message += cou + " "
    if message != "":
        flash(message + 'successfully added!', 'success')
    else:
        flash('all the courses is already used ', 'danger')
    return redirect((url_for('admin.AdminAccount')))

iSchoolApp/main_page/routes.py
# import stuff of flask
from flask import render_template, request, redirect, url_for, flash, send_file, Blueprint

main_page = Blueprint('main_page', __name__)


# home page
@main_page.route("/")
def home():
    return render_template('index.html')


@main_page.route("/about")
def about():
    return render_template('about.html')

iSchoolApp/teacher/routes.py
# import stuff of flask
from flask import render_template, request, redirect, url_for, flash, send_file, Blueprint

from iSchoolApp.teacher.forms import LoginForm, UpdateAccountForm, RegistrationForm

# getting access to application in app folder and to database and to bcrypt of password
from iSchoolApp import db, handleImageUploads, recognize_video, bcrypt

# import flask_login for login account
from flask_login import login_user, current_user, logout_user, login_required

from iSchoolApp.manegeReport import startClassFunc, endClassFunc

import xlsxwriter
from datetime import datetime

# import the database from app folder in file models
from iSchoolApp.models import User, Lecture, Administer, Report, Date, \
    Attendance

teacher = Blueprint('teacher', __name__)


# import form of register and login from app folder


def getListOfCourseAvailable(listOfCourses):
    newListOfCourses = []
    for crs in listOfCourses:
        if not User.query.filter_by(id=crs.user_id).first():
            newListOfCourses.append(crs)
        else:
            print("&&&&&&")
            print(User.query.filter_by(id=crs.user_id).first())
            print("&&&&&&")
    return newListOfCourses


# Handler in register users
@teacher.route("/register", methods=['GET', 'POST'])
def register():
    #if current_user.is_authenticated:
    #    return redirect(url_for('main_page.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        # user = User(username=form.username.data, email=form.email.data, password=form.password.data)
        # get a connection to save data in database
        db.session.add(user)
        # save data in database
        db.session.commit()
        courses = request.form.getlist("course[]")
        if courses:
            for cou in courses:
                print(user.get_id())
                c = Lecture.query.filter_by(nameOfLecture=cou).first()
                c.user_id = user.get_id()
                db.session.commit()
                print("===")
                print(cou)
                print("===")
            flash('Your account has been created ! You are now able to log in ', 'success')
            return redirect(url_for('teacher.login'))
        else:
            flash('Register Unsuccessful. Please choice course', 'danger')

    course_list = getListOfCourseAvailable(Lecture.query.all())
    return render_template('register.html', form=form, course_list=course_list)


# Handler in login users
@teacher.route("/login", methods=['GET', 'POST'])
def login():
    # check if the user is authenticated then send him to home page
    if current_user.is_authenticated:
        return redirect(url_for('main_page.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # check if email and password ok
        if user and bcrypt.check_password_hash(user.password, form.password.data):
        # if user and user.password == form.password.data:
            login_user(user, remember=form.remember.data)
            # if the user try to get to account and he logout so when he will be login he get the page
            next_page = request.args.get('next')
            if next_page:
                print("1")
                return redirect(next_page)
            else:
                print("2")
                return redirect((url_for('teacher.account')))
            # return redirect(next_page) if next_page else redirect((url_for('home')))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', form=form)


@teacher.route("/logout")
def logout():
    logout_user()
    # send the user to home page
    return redirect((url_for('main_page.home')))


@teacher.route("/account")
# check if the user is login before and then he send you to account page
@login_required
def account():
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    course_list = current_user.lecture
    return render_template('account.html', image_file=image_file, course_list=course_list)


@teacher.route("/updateAccountDetails", methods=['GET', 'POST'])
@login_required
def updateAccountDetails():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.email = form.email.data
        db.session.commit()
        flash('your account has been updated!', 'success')
        return redirect(url_for('teacher.account'))
    elif request.method == 'GET':
        form.email.data = current_user.email
    return render_template('updateAccountDetails.html', form=form)


@teacher.route("/course", methods=['GET'])
@login_required
def course():
    course_list = current_user.lecture
    print(course_list)
    size = len(course_list)
    if size > 0:
        return render_template('course.html', course_list=course_list, size=size)
    else:
        flash('You don\'t  have courses', 'danger')
        return redirect((url_for('teacher.account')))


# execute our software of face recognition
@teacher.route('/execute', methods=['GET', 'POST'])
def execute():
    dataStart = -1
    dataEnd = -1
    print("=====")
    data = request.get_json()
    print(data['id'])
    print(data['name'])
    print("=====")
    flag_bool = False
    lec = Lecture.query.filter_by(id=int(data['id'])).first()
    print("$$$$$$")
    for std in lec.students:
        flag_bool = True
    print(flag_bool)
    print("$$$$$$")
    if not flag_bool:
        print("bla bla")
        flash('You don\'t  have courses', 'danger')
        flash('You dont have students in this class', 'danger')
        return redirect(url_for('teacher.course'))

    if data['name'] == "courseIdStart":
        startClassFunc(int(data['id']))

    if data['name'] == "courseIdEnd":
        endClassFunc(int(data['id']))

    return redirect((url_for('teacher.course')))


@teacher.route('/report', methods=['GET', 'POST'])
def report():
    print("=====")
    # data = request.get_json()
    courseId = request.form.get("courseIdReport")
    print(courseId)
    # print(data['name'])
    print("=====")

    lec = Lecture.query.filter_by(id=courseId).first()
    c_name = lec.nameOfLecture
    rep = Report.query.filter_by(course_id=courseId).first()
    list_of_dates = rep.course_date
    std_list_of_lecture = lec.students
    return render_template('report.html', list_of_dates=list_of_dates, std_list_of_lecture=std_list_of_lecture,
                           c_name=c_name, courseId=courseId)


def getLenClass(start, end):
    time_1 = datetime.combine(datetime.now().date(), start.time())
    time_2 = datetime.combine(datetime.now().date(), end.time())

    time_elapsed = time_2 - time_1
    print(time_elapsed)
    return (datetime.min + time_elapsed).time()


def getPreOfAtt(sumOfLesson, lenOfClass):
    date_time1 = datetime.strptime(sumOfLesson, "%H:%M:%S.%f")
    date_time2 = datetime.strptime(lenOfClass, "%H:%M:%S.%f")

    print(date_time1)
    print(date_time2)

    a_timedelta1 = date_time1 - datetime(1900, 1, 1)
    seconds1 = a_timedelta1.total_seconds()

    a_timedelta2 = date_time2 - datetime(1900, 1, 1)
    seconds2 = a_timedelta2.total_seconds()
    print(seconds1)
    print(seconds2)
    return seconds1 / seconds2


@teacher.route('/datesExport', methods=['POST'])
def datesExport():
    date = request.form.get("dates")
    justDate = date.split(' ')
    fileName = justDate[0]
    dateObj = Date.query.filter_by(lesson_date=date).first()
    repObj = Report.query.filter_by(course_id=dateObj.att_rep).first()
    pathOfXLSX = "cache\\" + repObj.course_name + fileName + ".xlsx"

    rep = xlsxwriter.Workbook(pathOfXLSX)
    worksheet = rep.add_worksheet()
    worksheet.write(0, 0, "id")
    worksheet.write(0, 1, "name")
    worksheet.write(0, 2, "sum of attendance")
    worksheet.write(0, 3, "percentage")

    i = 1
    attendance = Attendance.query.filter_by(date_course=date).all()
    for att in attendance:
        print(att.student_name)
        sumOfLesson = str(att.sum).split(' ')
        if sumOfLesson[0] != 'None':
            dateCourse = Date.query.filter_by(lesson_date=att.date_course).first()
            len_of_class = getLenClass(dateCourse.start_class, dateCourse.end_class)
            percentageAttendance = getPreOfAtt(sumOfLesson[1], str(len_of_class))
            worksheet.write(i, 2, sumOfLesson[1])
            worksheet.write(i, 3, round(percentageAttendance, 2) * 100)
        else:
            worksheet.write(i, 2, 0)
            worksheet.write(i, 3, 0)

        worksheet.write(i, 0, att.student_id)
        worksheet.write(i, 1, att.student_name)

        i += 1
    rep.close()

    try:
        fileName = pathOfXLSX.split("\\")
        return send_file("../" + pathOfXLSX, attachment_filename=fileName[1], as_attachment=True)
    except Exception as e:
        return str(e)
    print("---------------------")

    return redirect((url_for('teacher.course')))


@teacher.route('/studentsExport', methods=['POST'])
def studentsExport():
    std = request.form.get("student")
    pathOfXLSX = "cache\\" + std + ".xlsx"
    rep = xlsxwriter.Workbook(pathOfXLSX)
    worksheet = rep.add_worksheet()
    worksheet.write(0, 0, "date")
    worksheet.write(0, 1, "sum of attendance")
    worksheet.write(0, 2, "length of class")
    worksheet.write(0, 3, "percentage")

    i = 1
    attendance = Attendance.query.filter_by(student_name=std).all()
    for att in attendance:
        dateCourse = Date.query.filter_by(lesson_date=att.date_course).first()
        len_of_class = getLenClass(dateCourse.start_class, dateCourse.end_class)

        print("*****")
        print(type(len_of_class))
        print("*****")

        dateLesson = str(att.dateOfLesson)

iSchoolApp/templates/AdminAccount.html
{% extends "layout.html" %}
{% block content %}



    <div class="container">
    <div class="line-section">

        <br>
        <a href="{{ url_for('admin.logoutAdmin')}}" type="button" class="btn btn-outline-secondary">Logout</a>
        <hr>

        <h3>Turn on/off the cameras of the school</h3>
        <form action="/onOffCameras" method="post" enctype="multipart/form-data">
            <button style="text-align: center" type="submit" class="btn btn-outline-secondary" name="button" value="1">ON</button>
            <button style="text-align: center" type="submit" class="btn btn-outline-secondary" name="button" value="0">OFF</button>
        </form>

        <br>
        <hr>
        <h3>Add a new teacher</h3>

        <a href="/register" type="button" class="btn btn-outline-secondary">To Register</a><br>
        <br>
        <hr>

         <br>
        <h3>Add camera</h3>

        <form action="/registerCam" method="post" enctype="multipart/form-data">

           Camera IP:<br>
           <input type="text" name="IP"><br>
           Class number:<br>
           <input type="text" name="class"><br>
            Status:<br>
           <input type="text" name="status"><br>

           <input type="submit" value="Upload" class="btn btn-outline-secondary"/>
       </form>
        <br>
        <hr>
        <h3>Add course</h3>
        <form action="/addCourse" method="post" enctype="multipart/form-data">

           Course name:<br>
           <input type="text" name="name"><br>
            Class number:<br>
           <input type="number" name="classNum"><br>
            Percentage of attendance:<br>
           <input type="number" name="percentage"><br>
           <input type="submit" value="Upload" class="btn btn-outline-secondary"/>
       </form>
        <hr>


        <br>
        <h3>Add courses to teacher</h3>
        <form action="/addCourseToTeacher" method="post" enctype="multipart/form-data">
            Teacher name:<br>
            <input type="text" name="teacher_name" required><br>
            Teacher id:<br>
            <input type="text" name="teacher_id" required><br>

           <div class="multiselect">
               <div class="selectBox" onclick="showCheckboxes_2()">
                   <label>Choose courses:</label>
                   <select>
                       <option></option>
                   </select>
                   <div class="overSelect"></div>
                   </div>
               <div id="checkboxes_2">
                   {% for crs in course_list %}
                   <label>
                       <input type="checkbox" value="{{crs.nameOfLecture}}" name="course[]" />{{crs.nameOfLecture}} - {{crs.id}}</label>
                   {% endfor %}
               </div>
           </div>
            <input type="submit" value="Upload" class="btn btn-outline-secondary"/>
        </form>


        <hr>
        <br>
        <h3>Add and modify student </h3>

        <form action="/handleImageUpload" method="post" enctype="multipart/form-data">
          <!-- Choose the file: <input type="file" name="photo"/><br>-->
           <div class="form-group">
            <label for="exampleFormControlFile1">Choose student image...</label>
            <input type="file" style="width:50%" class="form-control-file" name="photo" id="exampleFormControlFile1">
           </div>
           Enter Name Of Student:<br>
           <input type="text" name="name" required><br>
           Enter ID Of Student:<br>
           <input type="text" name="ID" required><br>
           <div class="multiselect">
               <div class="selectBox" onclick="showCheckboxes()">
                   <label>Choose courses:</label>
                   <select>
                       <option></option>
                   </select>
                   <div class="overSelect"></div>
                   </div>
               <div id="checkboxes">
                   {% for crs in course_list %}
                   <label>
                       <input type="checkbox" value="{{crs.nameOfLecture}}" name="course[]" />{{crs.nameOfLecture}} - {{crs.id}}</label>
                   {% endfor %}
               </div>
           </div>
            <br>
           <input type="submit" value="Upload" class="btn btn-outline-secondary"/>
       </form>
        <br>
        <hr>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12">
               <h3>Train the model</h3>
                <button style="text-align: center" id="train_btn" type="button" class="btn btn-outline-secondary">Train</button>
                <div id="spin" class="spinner-border text-secondary" role="status">
                  <span class="sr-only">training...</span>
                </div>
            </div>
        </div>
        <br>
    </div>
    </div>

<script>

    let $j = jQuery.noConflict();


    document.getElementById("train_btn").onclick =  function() {
        document.getElementById("spin").style.display = 'block';
            $j.get('/train',
            console.log("ok")
            ).done(function () {
                document.getElementById("spin").style.display = 'none';
            })
        };


    var expanded_1 = false;

    function showCheckboxes() {
      var checkboxes_1 = document.getElementById("checkboxes");
      if (!expanded_1) {
        checkboxes_1.style.display = "block";
        expanded_1 = true;
      } else {
        checkboxes_1.style.display = "none";
        expanded_1 = false;
      }
    }


    var expanded_2 = false;

    function showCheckboxes_2() {
      var checkboxes_2 = document.getElementById("checkboxes_2");
      if (!expanded_2) {
        checkboxes_2.style.display = "block";
        expanded_2 = true;
      } else {
        checkboxes_2.style.display = "none";
        expanded_2 = false;
      }
    }
</script>
{% endblock content %}

iSchoolApp/templates/account.html
{% extends "layout.html" %}
{% block content %}


<div class="container">

    <br><br>
        <div class="content-section">
          <div class="media">

            <img class="rounded-circle account-img" src="{{ image_file }}">

            <div class="media-body">

              <h2 class="account-heading">{{ current_user.username }}</h2>

                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
          </div>
        </div>

        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-12 btn-teacher">
                <a href="{{ url_for('teacher.course')}}" type="button" class="btn btn-outline-secondary">Your courses</a>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-12 btn-teacher">
                <a href="{{ url_for('teacher.updateAccountDetails')}}" type="button" class="btn btn-outline-secondary">Update info</a>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-12 btn-teacher">
                <a href="{{ url_for('teacher.logout')}}" type="button" class="btn btn-outline-secondary">Logout</a>
            </div>
        </div>


</div>

{% endblock content %}

iSchoolApp/templates/addCourse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

iSchoolApp/templates/index.html
{% extends "layout.html" %}
{% block content %}


    <section class="main-section">
        <div class="overlay">
        <div class="max-layout centerItems">
            <div class="title-site">
                <h1>i-School</h1>
                <p>Face Recognition based attendance system</p>
            </div>
        </div>
        </div>
    </section>

<div class="container">
    <h3 class="title-section"><span class="first-word-title"></span>The <span class="dot-title">Challenge</span>.</h3>
    <div class="row">
        <!--<div class="max-layout centerItems">-->
            <div class="problem_case">

                <ul>
                    <h5>Algorithm</h5>
                    <li>Finding an existing reliable Face Recognition Algorithm from an open source code.</li>
                    <li>An algorithm which requires a reasonable amount of face images per student.</li>
                    <li>Models of face detection from multiple position such as frontal right and left face profiles.</li><br>
                    <h5>System</h5>
                    <li>Reduce attendance time.</li>
                    <li>Constant tracking student attendance in all classrooms at any given moment.</li>
                    <li>Tracking the time each student has been present in the classroom during the lesson.</li>
                </ul>
            </div>
        <!--</div>-->
    </div>
</div>

<section class="sectionDark">
    <div class="container"><!--<div class="max-layout centerItems">-->
            <h3 class="title-section"><span class="first-word-title"></span>The <span class="dot-title">Solution</span>.</h3>
            <div class="row">
                <div class="col-lg-6 col-md-12 context-solution">
                    <p>
                        i-School is an AI powered face recognition solution
                        which uses Computer Vision and Machine
                        Learning algorithms to mark the attendance of students in school.<br><br>
                       <!-- Using a range of algorithms that cv2.dnn provides for face detection, embedding extraction and
                        recognition in real time.-->

                    </p>
                   <!-- <p>
                        The system will work on face recognition where each student in the class will be photographed and
                        their details will be stored in a server. The teacher can then start attendance by
                        clicking start/end class button.
                    </p>-->
                </div>
                <div class="col-lg-1">
                </div>
                <div class="col-lg-5 col-md-12">
                    <div class="img-solution">
                        <img src="../static/frame_0_delay-s.jpg" >
                    </div>
                </div>
        </div>
    </div>
</section>

<div class="container">
    <section class="solution-section">
        <!--<div class="max-layout centerItems">-->
            <div>
                <h3 class="title-section"><span class="first-word-title"></span>How it <span class="dot-title">Works</span>.</h3>
                <div class="row">
                    <div class="col-lg-5 col-md-10">
                        <div class="img-solution">
                            <img src="../static/b.jpg" >
                        </div>
                    </div>
                    <div class="col-lg-1">
                    </div>
                    <div class="col-lg-6 col-md-12 context-solution">
                        <p>
                            Using a range of algorithms that cv2.dnn provides for face detection, embedding extraction and
                        recognition in real time.
                           The system will work on face recognition where each student in the class will be photographed and
                        their details will be stored in a server. The teacher can then start attendance by
                        clicking start/end class button.
                        </p>
                        <p>
                          <!-- Using a range of algorithms that cv2.dnn provides for face detection, embedding extraction and
                        recognition in real time.-->
                        </p>
                    </div>
                </div>
            </div>

        <!--</div>-->
        <div style="text-align: center" class="col-lg-12">
        <a href="{{ url_for('main_page.about')}}" type="button" class="btn btn-outline-secondary">KNOW MORE</a>
        </div>
    </section>
</div>
<br><br>
<section class="impact-section">
    <div class="container">
        <h3 class="title-section"><span class="first-word-title"></span>The <span class="dot-title">Impact</span>.</h3>
        <div class="row">
            <div class="col-lg-6 col-sm-12" style="margin-bottom: 20px">
                <div class="card cardImpact">
                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-sm-3">
                            <img style="margin: 15px 15px" src="https://img.icons8.com/pastel-glyph/64/000000/time.png"/>
                        </div>
                        <div class="col-lg-9 col-md-9 col-sm-9">
                            <h5 class="card-title">Saves Time</h5>
                            <p>With face recognition in place, students can’t mark proxy attendance.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-sm-12" style="margin-bottom: 20px">
                <div class="card cardImpact">
                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-sm-3">
                            <img style="margin: 15px 15px" src="https://img.icons8.com/wired/64/000000/id-not-verified.png"/>
                        </div>
                        <div class="col-lg-9 col-md-9 col-sm-9">
                            <h5 class="card-title">Reliability</h5>
                            <p>With face recognition in place, students can’t mark proxy attendance.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-sm-12" style="margin-bottom: 20px">
                <div class="card cardImpact">
                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-sm-3">
                            <img style="margin: 15px 15px" src="https://img.icons8.com/dotty/80/000000/time-management.png"/>
                        </div>
                        <div class="col-lg-9 col-md-9 col-sm-9">
                            <h5 class="card-title">Increases productivity</h5>
                            <p>With admin work taken care of, teachers and admins can focus on more productive work.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-sm-12" style="margin-bottom: 20px">
                <div class="card cardImpact">
                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-sm-3">
                            <img style="margin: 15px 15px" src="https://img.icons8.com/dotty/80/000000/error--v1.png"/>
                        </div>
                        <div class="col-lg-9 col-md-9 col-sm-9">
                            <h5 class="card-title">Eliminate human error</h5>
                            <p>Based on artificial intelligence, this system will completely eliminate any chances
                                of human error.
                                The system is equipped with state of the art face detection and recognition algorithms,
                                making it completely foolproof.</p>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</section>


{% endblock content %}

iSchoolApp/templates/report.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">


        <br>
        <div class="repo">
            <h1>Report</h1>
            <h3>{{c_name}} - {{courseId}}</h3>
        </div>

        <div class="row">
            <div class="col-lg-6 col-sm-12">
                <form action="/datesExport" method="post">
                    <label for="dates"><h6>By date:</h6></label>
                    <select name="dates" id="dates" class="custom-select custom-select-lg mb-3" required>
                        {% for d in list_of_dates %}
                      <option value="{{d.lesson_date}}" name="date_num">{{d.lesson_date.date()}}</option>
                        {% endfor %}
                    </select>
                    <button type="submit" class="btn btn-outline-info">Download Excel</button>
                </form>
                <br>
            </div>

            <div class="col-lg-6 col-sm-12">
                <form action="/studentsExport" method="post">
                    <label for="student"><h6>By student:</h6></label>
                    <select name="student" id="student" class="custom-select custom-select-lg mb-3" required>
                        {% for std in std_list_of_lecture %}
                      <option value="{{std.nameOfStudent}}" name="std_name">{{std.nameOfStudent}} - {{std.id}}</option>
                        {% endfor %}
                    </select>
                    <button type="submit" class="btn btn-outline-info">Download Excel</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}